FROM n8nio/n8n:latest

ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=admin
ENV N8N_BASIC_AUTH_PASSWORD=financialfeeling2024
ENV N8N_HOST=0.0.0.0
ENV N8N_PORT=5678
ENV N8N_PROTOCOL=https
ENV WEBHOOK_URL=${WEBHOOK_URL}
ENV GENERIC_TIMEZONE=America/New_York
ENV N8N_ENCRYPTION_KEY=financialfeeling2024encryptionkey32

EXPOSE 5678
CMD ["n8n", "start"]
